"""Replay saved frames through perception, offline. No game, no services, no GPU.

WHY
---
Until now, testing a perception change meant: restart 14 uvicorn services, launch a
real UNO match, watch the operator, grep four log files. Thirty minutes per
hypothesis, and irreproducible — the board differed every run, so "it looks better"
was the strongest statement anyone could make.

This script closes that loop. It takes frames captured by `uno_shared.cycle_trace`
during real play, re-runs recognition over them, and diffs the result against a
hand-labelled expectation. Seconds per run, byte-identical inputs every time.

That matters most for the multi-game goal: when Svintus support lands, the only way
to know UNO still works is to re-run UNO's corpus. Process isolation between
microservices does not give you that; a corpus does.

USAGE
-----
Grow the corpus from a real session (copies the frame, writes a labelling stub):

    python scripts/replay_perception.py promote artifacts/cycle_trace/<sess>/0007 \
        --game uno --case in_game_red6

Then open the new `expected.json` and correct it BY HAND against the frame. The
label is the ground truth — never generated by the thing being tested.

Score the corpus (exit code 1 if accuracy is below the threshold, so CI can gate):

    python scripts/replay_perception.py run --game uno
    python scripts/replay_perception.py run --recognizer vlm       # exercise Ollama
    python scripts/replay_perception.py run --case in_game_red6 -v # one case, verbose

CORPUS LAYOUT
-------------
    tests/fixtures/perception/<game>/<case>/frame.png
    tests/fixtures/perception/<game>/<case>/expected.json

`expected.json` holds only what a human vouched for. Any key that is absent is not
compared, so a partially-labelled case is still useful:

    {
      "screen_type": "in_game",
      "top_card": {"color": "red", "value": "6"},
      "hand_cards": [{"color": "red", "value": "6"}, {"color": "blue", "value": "9"}],
      "notes": "Task Manager overlapped the right edge of the hand"
    }
"""

from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import sys
import time
from collections import Counter
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
CORPUS_ROOT = REPO_ROOT / "tests" / "fixtures" / "perception"

# The services are separate packages; this script is not one of them. Add the source
# roots explicitly so the harness runs from a bare checkout without an editable
# install — and, more importantly, so it always tests THIS working tree. Editable
# installs of a sibling project have already shadowed this repo once (AGENT_LOG.md
# 2026-08-04), and a harness that silently scores someone else's code is worse than
# no harness.
for _src in (
  REPO_ROOT / "services" / "perception-service" / "src",
  REPO_ROOT / "services" / "uno-core" / "src",
  REPO_ROOT / "packages" / "schemas" / "src",
  REPO_ROOT / "packages" / "shared-utils" / "src",
):
  if _src.is_dir() and str(_src) not in sys.path:
    sys.path.insert(0, str(_src))


def _load_perception():
  """Import the perception entry points late, with an actionable error message."""
  try:
    from uno_perception.merger import build_observation
    from uno_perception.vlm_provider import infer_vision
    from uno_schemas.perception import ScreenshotFrame
  except ImportError as exc:
    raise SystemExit(
      f"Cannot import perception ({exc}).\n"
      "Run this with the repo venv: .\\.venv\\Scripts\\python.exe scripts/replay_perception.py ..."
    ) from exc
  return build_observation, infer_vision, ScreenshotFrame


# ── card comparison ──────────────────────────────────────────────────────────────

def _norm_card(card: Any) -> tuple[str, str] | None:
  """Reduce a card to (color, value), lowercased. Returns None for junk."""
  if not isinstance(card, dict):
    return None
  color = str(card.get("color") or "").strip().lower()
  raw_value = card.get("value")
  if raw_value is None:
    raw_value = card.get("number")
  value = str(raw_value if raw_value is not None else "").strip().lower()
  if not color and not value:
    return None
  return (color, value)


def _norm_hand(cards: Any) -> Counter:
  """Hand as a MULTISET, not a list.

  Order is not ground truth: the hand is fanned and rotated, and left-to-right
  ordering shifts as cards are played. Comparing lists would report a failure for a
  perfectly-read hand that happens to be enumerated differently. Duplicates DO
  matter (two red 6s is not one red 6), hence Counter rather than set.
  """
  out: Counter = Counter()
  for c in cards or []:
    n = _norm_card(c)
    if n is not None:
      out[n] += 1
  return out


def _fmt_card(card: tuple[str, str]) -> str:
  color, value = card
  return f"{color or '?'}-{value or '?'}"


def _fmt_hand(counter: Counter) -> str:
  if not counter:
    return "(empty)"
  return ", ".join(sorted(f"{_fmt_card(c)}×{n}" if n > 1 else _fmt_card(c) for c, n in counter.items()))


# ── one case ─────────────────────────────────────────────────────────────────────

def _frame_size(path: Path) -> tuple[int, int]:
  try:
    from PIL import Image
    with Image.open(path) as im:
      return int(im.width), int(im.height)
  except Exception:
    return 1, 1


async def _perceive_frame(frame: Path, game: str, recognizer: str) -> dict[str, Any]:
  """Run the SAME path the service runs, minus HTTP.

  Mirrors `uno_perception.api.perceive`: optionally invoke the VLM, then hand the
  result to `build_observation`. If those two ever diverge this harness stops being
  evidence, so keep them in step.
  """
  build_observation, infer_vision, ScreenshotFrame = _load_perception()
  width, height = _frame_size(frame)
  shot = ScreenshotFrame(
    frame_id=f"replay_{frame.parent.name}",
    session_id="replay",
    width=width,
    height=height,
    path=str(frame),
    captured_at_ms=int(time.time() * 1000),
  )
  vlm = None
  vlm_status = "skipped"
  if recognizer == "vlm":
    vlm, vlm_status = await infer_vision(str(frame), game_type=game)
  obs = build_observation("replay", screenshot=shot, vlm=vlm, game_type=game)
  gs = dict(obs.game_state or {})
  gs.setdefault("vlm_status", vlm_status)
  gs["_confidence"] = {
    "overall": obs.confidence.overall,
    "game_state": obs.confidence.game_state,
  }
  return gs


def _compare(expected: dict[str, Any], actual: dict[str, Any]) -> tuple[bool, list[str]]:
  """Compare only the keys the label actually asserts.

  A half-labelled case still earns its keep, and nobody is forced to transcribe all
  nine cards before they can assert the screen type.
  """
  problems: list[str] = []

  if "screen_type" in expected:
    exp = str(expected["screen_type"]).lower()
    got = str(actual.get("screen_type") or "").lower()
    if exp != got:
      problems.append(f"screen_type: expected {exp!r}, got {got!r}")

  if "whose_turn" in expected:
    exp = str(expected["whose_turn"]).lower()
    got = str(actual.get("whose_turn") or "").lower()
    if exp != got:
      problems.append(f"whose_turn: expected {exp!r}, got {got!r}")

  if "top_card" in expected:
    exp_card = _norm_card(expected["top_card"])
    got_card = _norm_card(actual.get("top_card"))
    if exp_card != got_card:
      problems.append(
        f"top_card: expected {_fmt_card(exp_card) if exp_card else 'none'}, "
        f"got {_fmt_card(got_card) if got_card else 'none'}"
      )

  if "hand_cards" in expected:
    exp_hand = _norm_hand(expected["hand_cards"])
    got_hand = _norm_hand(actual.get("hand_cards"))
    if exp_hand != got_hand:
      missing = exp_hand - got_hand
      extra = got_hand - exp_hand
      detail = []
      if missing:
        detail.append(f"missed {_fmt_hand(missing)}")
      if extra:
        detail.append(f"invented {_fmt_hand(extra)}")
      problems.append(
        f"hand_cards ({sum(exp_hand.values())} expected, {sum(got_hand.values())} read): "
        + "; ".join(detail)
      )

  if "hand_count" in expected:
    exp_n = int(expected["hand_count"])
    got_n = len(actual.get("hand_cards") or [])
    if exp_n != got_n:
      problems.append(f"hand_count: expected {exp_n}, got {got_n}")

  return (not problems), problems


def discover_cases(game: str | None = None, case: str | None = None) -> list[Path]:
  """Corpus case directories: every dir holding both frame.* and expected.json."""
  if not CORPUS_ROOT.is_dir():
    return []
  games = [CORPUS_ROOT / game] if game else [d for d in CORPUS_ROOT.iterdir() if d.is_dir()]
  found: list[Path] = []
  for gdir in games:
    if not gdir.is_dir():
      continue
    for cdir in sorted(gdir.iterdir()):
      if not cdir.is_dir() or (case and cdir.name != case):
        continue
      if (cdir / "expected.json").is_file() and any(cdir.glob("frame.*")):
        found.append(cdir)
  return found


async def run_corpus(
  game: str | None, case: str | None, recognizer: str, verbose: bool
) -> tuple[int, int, list[str]]:
  cases = discover_cases(game, case)
  if not cases:
    return 0, 0, []
  passed = 0
  failures: list[str] = []
  for cdir in cases:
    frame = next(iter(sorted(cdir.glob("frame.*"))))
    expected = json.loads((cdir / "expected.json").read_text(encoding="utf-8"))
    label = f"{cdir.parent.name}/{cdir.name}"
    try:
      actual = await _perceive_frame(frame, cdir.parent.name, recognizer)
    except Exception as exc:  # noqa: BLE001 — a crash is a failed case, not a crashed run
      failures.append(f"{label}: raised {type(exc).__name__}: {exc}")
      print(f"ERROR {label}: {type(exc).__name__}: {exc}")
      continue
    ok, problems = _compare(expected, actual)
    if ok:
      passed += 1
      print(f"  ok  {label}")
    else:
      failures.append(f"{label}: " + " | ".join(problems))
      print(f"FAIL  {label}")
      for p in problems:
        print(f"        {p}")
    if verbose:
      print(f"        recognizer={actual.get('recognition_method')} vlm={actual.get('vlm_status')} "
            f"conf={actual.get('_confidence')}")
      print(f"        read hand: {_fmt_hand(_norm_hand(actual.get('hand_cards')))}")
  return passed, len(cases), failures


# ── promote a live trace into the corpus ─────────────────────────────────────────

def promote(trace_dir: Path, game: str, case: str, force: bool) -> int:
  cycle_json = trace_dir / "cycle.json"
  if not cycle_json.is_file():
    print(f"No cycle.json in {trace_dir} — is that a cycle-trace directory?")
    return 1
  record = json.loads(cycle_json.read_text(encoding="utf-8"))
  frames = sorted(trace_dir.glob("frame.*"))
  if not frames:
    print(f"No frame.* in {trace_dir} — the cycle ran without a screenshot, nothing to label.")
    return 1

  dest = CORPUS_ROOT / game / case
  if dest.exists() and not force:
    print(f"{dest} already exists (use --force to overwrite)")
    return 1
  dest.mkdir(parents=True, exist_ok=True)
  shutil.copyfile(frames[0], dest / frames[0].name)

  perceived = record.get("perception") or {}
  # The stub is PRE-FILLED WITH WHAT THE AGENT SAW, which is the thing under test —
  # so it is a starting point for transcription, never the label itself. Accepting it
  # unread would enshrine the current bug as the expected answer, and the corpus
  # would then "pass" forever while the agent plays a hand that isn't on screen.
  stub = {
    "_TODO": "Verify EVERY field against frame by eye, then delete this key.",
    "_provenance": record.get("provenance"),
    "screen_type": perceived.get("screen_type"),
    "whose_turn": perceived.get("whose_turn"),
    "top_card": perceived.get("top_card"),
    "hand_cards": perceived.get("hand_cards") or [],
    "notes": "",
  }
  (dest / "expected.json").write_text(
    json.dumps(stub, indent=2, ensure_ascii=False), encoding="utf-8"
  )
  print(f"Promoted {trace_dir} → {dest}")
  print(f"  frame: {dest / frames[0].name}")
  print(f"  NOW EDIT BY HAND: {dest / 'expected.json'}  (it currently holds the agent's own guess)")
  return 0


def main() -> int:
  parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  sub = parser.add_subparsers(dest="cmd", required=True)

  run_p = sub.add_parser("run", help="score the corpus")
  run_p.add_argument("--game", default=None, help="limit to one game (e.g. uno)")
  run_p.add_argument("--case", default=None, help="limit to one case directory")
  run_p.add_argument("--recognizer", choices=("heuristic", "vlm"), default="heuristic",
                     help="heuristic = deterministic, no model. vlm = call the model (slow, needs Ollama)")
  run_p.add_argument("--min-accuracy", type=float, default=1.0,
                     help="exit 1 below this pass ratio (default 1.0)")
  run_p.add_argument("-v", "--verbose", action="store_true")

  prom = sub.add_parser("promote", help="copy a cycle-trace dir into the corpus for labelling")
  prom.add_argument("trace_dir", type=Path)
  prom.add_argument("--game", required=True)
  prom.add_argument("--case", required=True)
  prom.add_argument("--force", action="store_true")

  args = parser.parse_args()

  if args.cmd == "promote":
    return promote(args.trace_dir, args.game, args.case, args.force)

  passed, total, failures = asyncio.run(
    run_corpus(args.game, args.case, args.recognizer, args.verbose)
  )
  if total == 0:
    print(f"No labelled cases under {CORPUS_ROOT}.")
    print("Play a session with AGENT_CYCLE_TRACE=1, then:")
    print("  python scripts/replay_perception.py promote artifacts/cycle_trace/<session>/0001 "
          "--game uno --case first_case")
    return 0
  accuracy = passed / total
  print(f"\n{passed}/{total} cases pass ({accuracy:.0%}), recognizer={args.recognizer}")
  if failures and accuracy < args.min_accuracy:
    print(f"Below --min-accuracy {args.min_accuracy:.0%}")
    return 1
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
